name: testing

on:
  push:
    branches:
      - main

jobs:
  # Run only for changed packages.
  changes:
    runs-on: ubuntu-latest
    name: Detect changed packages
    # Set job outputs to values from filter step
    outputs:
      systems: ${{ steps.filter.outputs.systems }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          systems:
            - "packages/systems/**"

  # Test jobs per package.
  systems:
    name: Test @eve-data/systems
    needs: changes
    if: ${{ needs.changes.outputs.systems == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "16"
      - name: Install dependencies
        working-directory: packages/systems
        run: npm ci
      - name: Run linter
        working-directory: packages/systems
        run: npm run lint
      - name: Run tests
        working-directory: packages/systems
        run: npm test
